# Generated by Django 5.2.4 on 2026-05-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
