# Generated by Django 5.2.4 on 2026-05-30 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_contact_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
